name: fix-apx-config
type: shell
commands:
  - >-
    mkdir -p /usr/share/apx;
    printf '%s\n'
    '{'
    '  "apxPath": "/usr/share/apx",'
    '  "distroboxPath": "/usr/share/apx/distrobox/distrobox",'
    '  "storageDriver": "overlay"'
    '}'
    > /usr/share/apx/apx.json