name: fix-apx-config
type: shell
commands:
  - mkdir -p /usr/share/apx
  - |
    cat > /usr/share/apx/apx.json <<'EOF'
    {
      "apxPath": "/usr/share/apx",
      "distroboxPath": "/usr/local/bin/distrobox",
      "storageDriver": "btrfs"
    }
    EOF